version: '3.5'

services:
        frontend:
                image: frontend1.7
                environment:
                        - API_URL=http://localhost:8000
                container_name: frontend2.1
                ports:
                        - 5000:5000
        backend:
                image: backend1.7
                environment:
                        - FRONT_URL=http://localhost:5000
                container_name: backend2.1
                ports:
                        - 8000:8000

