version: '3.5'

services:
        frontend:
                image: frontend1.7
                environment:
                        - API_URL=http://localhost:8000
                ports:
                        - 5000:5000
        backend:
                depends_on:
                        - redis
                image: backend1.7
                environment:
                        - FRONT_URL=http://localhost:5000
                        - REDIS=redis
                        - REDIS_PORT=6379
                ports:
                        - 8000:8000
        redis:
                image: redis

