version: '3.5'

services:
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
  frontend:
    image: frontend1.7
    environment:
      - API_URL=http://localhost/api
      - PORT=80
  backend:
    depends_on:
      - redis
      - db
    image: backend1.7
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=possu
      - DB_PASSWORD=jami
      - DB_HOST=db
  redis:
    image: redis
    volumes:
      - ./redis-data:/data
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=jami
      - POSTGRES_USER=possu
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
